config/routes.rb
Rails.application.routes.draw do

  resources :volunteers
  resources :transits

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :volunteers
end

app/models/transit.rb
class Transit < ActiveRecord::Base
	has_and_belongs_to_many :volunteers
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
	has_and_belongs_to_many :volunteers
	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transits_controller.rb
class TransitsController < ApplicationController
	def index
		@transits = Transit.all
	end

	def new
		@transit = Transit.new
	end

	def create
		@transit = Transit.new(transit_params)
	end

	private
	def transit_params
		params.require(:transportation).permit(mode)
	end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController

	def new
		@volunteer = Volunteer.new
	end

	def create
		@volunteer = Volunteer.new(volunteer_params)

		if @volunteer.save
			redirect_to new_transit_path
		else
			render 'new'
		end
	end

	def show
		@volunteer = Volunteer.find params[:id]
	end

	def index
		@volunteers = Volunteer.all
	end

	private
	def volunteer_params
		params.require(:volunteer).permit(:name, :surname, :email, :gender)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenupApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transits/new.html.erb
<h1>New Transit</h1>

app/views/volunteers/_form.html.erb
<%= simple_form_for(@volunteer) do |f| %>

	<% if @volunteer.errors.any? %>
		<h2>
			<%= pluralize(@volunteer.errors.count, "error") %> prohibted you from continuing. Please try again.
		</h2>
		<ul>
			<% @volunteers.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.input :name, placeholder: 'First Name Here' %><br>

	<%= f.input :surname, placeholder: 'Last Name Here' %><br>

	<%= f.input :email, placeholder: 'Your email' %>

	<%= f.submit 'Continue' %>

<% end %>

app/views/volunteers/new.html.erb
<h1>GreenUp Travel App</h1>

<h2>Please tell us a little about yourself and how we can reach you.</h2>

<%= render 'form' %>

<% @volunteer.save %>

<%= link_to "Back", root_path %>

app/views/welcome/index.html.erb
<h1>Hi there!</h1>
<h2>Welcome to this fun 5-minute calculator</br>
The aim is to inspire us all to live a little greener</h2>

<p><%= link_to "Get started!", new_volunteer_path %>


<!-- Or put sign-in first, then search bar on next page... -->
<!-- Put search bar here, or drop-down bar containing events -->